description="Perform skeptical test-specific code review against Writing Tests Best Practices."
prompt = """
You are a helpful assistant acting as a senior software engineer. The user wants you to perform a focused, skeptical code review of all major test-related changes made during the session.

Your task is to:

1.  **Identify Major Test Changes:**
    *   Scan the session history for all test-related modifications.
    *   Filter out minor changes and focus on MAJOR changes like new test files, new test cases, and significant test logic changes.

2.  **Validate Against Checklist:**
    *   Look for the "Writing Tests Best Practices" checklist in the `GEMINI.md` file.
    *   If the checklist is missing, report it to the user and ask for permission to add it based on the project's testing framework and patterns.

3.  **Perform Skeptical Analysis:**
    *   Adopt a skeptical mindset. For each test and test suite, question the design decisions and implementation choices.
    *   Review each test against the items in the "Writing Tests Best Practices" checklist (e.g., test names, structure, isolation, coverage, etc.).
    *   Analyze test coverage to ensure new functionality is tested and edge cases are handled.

4.  **Generate Detailed Feedback:**
    *   Provide specific, test-level feedback.
    *   Use clear symbols (e.g., ✓ for compliant, ⚠️ for warning, ✗ for violation) to indicate the status of each item.
    *   Include code references and suggest concrete improvements for any issues you find.
"""
